### PR TITLE
Update readme sdk url

### PR DESCRIPTION
**Pull request by nbrl**
As it says on the tin.

### CODE REVIEW

**Comment by jabclab** [comment]
At present we don't mention the fact that a minified version is available. Is that something we want to do?

**Comment by nbrl** [comment]
I was ignoring it for the time being as on the offchance someone finds an error and wants us to look into it, I'd much rather have the line number from the full version. That OK?

**Comment by jabclab** [comment]
@nbrl :+1:

**Comment by jabclab** [comment]
Would be worth considering use of [`gulp-sourcemaps`](https://www.npmjs.com/package/gulp-sourcemaps) at some point soon.

**Comment by nbrl** [comment]
Yep - I have a feeling `gulp-uglify` has this built-in as well.

**Comment by jabclab** [comment]
#60 raised to capture this.

**Comment by jabclab** [comment]
Do you think we want to always provide the SSL address? Will it ever cause issues with older browsers when the parent page is loading over HTTP? Would `//d22stxronnwc65.cloudfront.net/sdk-latest.js` be better?

**Comment by nbrl** [comment]
Don't mind - as long as assets are *more* secure than the parent it should be fine, but I can switch it.

**Comment by jabclab** [comment]
@nbrl :+1: CloudFront seems to redirect to SSL anyway:

```
~ ➜  curl http://d22stxronnwc65.cloudfront.net/sdk-latest.js --head                                                                   
HTTP/1.1 301 Moved Permanently
Server: CloudFront
Date: Mon, 29 Jun 2015 14:23:51 GMT
Content-Type: text/html
Content-Length: 183
Connection: keep-alive
Location: https://d22stxronnwc65.cloudfront.net/sdk-latest.js
X-Cache: Redirect from cloudfront
Via: 1.1 7de51069c6a64edc13f9b9fcad8a6c98.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 5BWncnaWsG-Nd6jS0Zf7ZiJ9PhgYmZhRus15n8s4yfyx06fQydcU5w==
```

**Pull request merged**
